allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.layout.buildDirectory.set(new File(rootProject.projectDir, "../build"))
subprojects {
    project.layout.buildDirectory.set(new File(rootProject.layout.buildDirectory.get().asFile, project.name))
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.layout.buildDirectory
}
